version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: viqi_postgres
    environment:
      POSTGRES_DB: viqi
      POSTGRES_USER: viqi_user
      POSTGRES_PASSWORD: viqi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viqi_user -d viqi"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: viqi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
